### ISSUE TITLE
Don’t reject formulae with satisfiable requirements

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-command-not-found#13]
See https://github.com/Homebrew/homebrew-command-not-found/commit/6604d6b4ce29a1ca9711fff930641f739fb56912#commitcomment-12479621

**Comment by mikemcquaid** [comment]
Related to this you may want to try and install casks to satisfy requirements.

**Comment by bfontaine** [comment]
@mikemcquaid Good idea; we can’t install casks but we can suggest the user to do so. This tool is only giving hints; it doesn’t actually install stuff.

**Comment by mikemcquaid** [comment]
Now that we autoinstall `cask` we could consider installing casks automatically if Cask is already on the system.
