### ISSUE TITLE
FISH support

### ISSUE THREAD

**Issue by lordlycastle** [Homebrew/homebrew-command-not-found#14]
Is there going to be FISH support? I tried following the instructions but, it doesn't work for FISH.

**Comment by bfontaine** [comment]
There is no Fish support for now, unfortunately.

**Comment by lordlycastle** [comment]
Any plans for the future?

**Comment by bfontaine** [comment]
I’d love to have Fish support, but as I’m not a Fish user I haven’t looked at it. Would you want to try a pull-request?

**Comment by lordlycastle** [comment]
Sure, would love to. It should be fairly straightforward. The `__fish_default_command_not_found` function is run on OS X, when `fish_command_not_found` event is emitted; unless when custom function (usually `__fish_command_not_found_handler`) function exists with the event. All you gotta do is create a custom function with the event, which is similar to `homebrew_command_not_found_handle()` in the formula.
