### ISSUE TITLE
Incorrectly refer to .bashrc as opposed to .bash_profile?

### ISSUE THREAD

**Issue by teunzwart** [Homebrew/homebrew-command-not-found#26]
On Mac OSX `.bashrc` is not sourced by default, but `.bash_profile` is.
In your readme you refer to `.bashrc`. Is this correct or do you mean `.bash_profile`?

**Comment by bfontaine** [comment]
Interesting. My `.bash_profile` sources my `.bashrc` but I guess I did put that myself.

**Comment by davelab6** [comment]
I also just ran into this when installing a brand new mac.

**Comment by bfontaine** [comment]
Sorry for the delay on this; I just fixed the README.
