### ISSUE TITLE
not working and I've installed and edited my bash_profile

### ISSUE THREAD

**Issue by perfekted** [Homebrew/homebrew-command-not-found#27]
still just shows up

$ when
-bash: when: command not found

$ brew tap homebrew/command-not-found
Warning: Tap homebrew/command-not-found already tapped.

.bash_profile
#   brew command not found
if brew command command-not-found-init > /dev/null; then eval "$(brew command-not-found-init)"; fi

**Comment by bfontaine** [comment]
What is the output of `brew which-formula when`?

**Comment by perfekted** [comment]
$ brew which-formula when
when

**Comment by perfekted** [comment]
I got it to work :) I upgraded my bash to 4.3 on my mac. thanks so much for ur help and this command

**Comment by bfontaine** [comment]
I’m glad you got it to work :smile: 
Bash under 4.x doesn’t have the needed feature for this so you need to upgrade it.

**Comment by davelab6** [comment]
> I got it to work :) I upgraded my bash to 4.3 on my mac. thanks so much for ur help and this command

This still doesn't work for me :(

**Comment by bfontaine** [comment]
@davelab6 Please open another issue.
