### ISSUE TITLE
Consider importing into Homebrew

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-command-not-found#3]
I think it'd be great to perhaps import this tool into Homebrew core at some point.

**Comment by bfontaine** [comment]
It still needs some work to be considered stable but I’d be glad to import it when it’ll be. We’ll need a way to automatically update the file database (by the bot?) instead of the manual `brew which-update` I use right now.

I need to clean up the tapped formulae (outside of `homebrew/*` taps) and to fix #2.

**Comment by bfontaine** [comment]
Both issues have been fixed now.

**Comment by mikemcquaid** [comment]
Yeh, the main thing is that file and where we keep it. I'm wondering if Git is the best place. Then again, it's text and unlikely to change.

**Comment by bfontaine** [comment]
Yes, it doesn’t need to be versioned, we could upload it on some host (e.g. Bintray) but when should it be updated on the client side? Having it in a tap means it’s updated when people run `brew update`, but it needs to be versioned for that :confused:

**Comment by mikemcquaid** [comment]
Yeh, hmm.

**Comment by bfontaine** [comment]
Note we now have Zsh support thanks to @xu-cheng :smile:

**Comment by xu-cheng** [comment]
@bfontaine May I ask how do you update the data? A bot or manually?

**Comment by bfontaine** [comment]
@xu-cheng Manually with [a script](https://github.com/bfontaine/homebrew-command-not-found/blob/master/cmd/brew-which-update.rb). When I run `brew update` I check if they are new formulae, if so I install them, run `brew which-update executables.txt`, commit and push. I’m considering a bot but don’t have the time to work on it right now.

**Comment by xu-cheng** [comment]
OK. When you consider a bot, I'm more than happy to add a webhook in Homebrew repo for it. I recently wrote a [Homebrew twitter bot](https://github.com/xu-cheng/tweetbrew) which you can use it as a reference if you want.

**Comment by bfontaine** [comment]
Great, thanks!

**Comment by mikemcquaid** [comment]
Or get it into `brew-test-bot`

**Comment by xu-cheng** [comment]
It should be a combination of `brew test-bot` and a separate bot. `brew test-bot` is responsible to record the executable fils and store them in temporary place, while a separate bot is used to update the database when PR is merging.

**Comment by mikemcquaid** [comment]
At the very least we could pull this into the Homebrew organisation for more visibility.

**Comment by bfontaine** [comment]
Done.

**Comment by mikemcquaid** [comment]
Thanks!

**Comment by mralexgray** [comment]
wait, if this is done, why is it still open?  or is it done?  or is it open?  i'm confused.  clarification is needed, as a (prezto)[https://github.com/sorin-ionescu/prezto] issue #847 depends on this being resolved, up here (upstream).

**Comment by bfontaine** [comment]
@mralexgray I moved the repo under the Homebrew organization; but having this feature into Homebrew itself requires significant work so it won’t happen in the near future.

**Comment by mikemcquaid** [comment]
Closing this issue out as it's a longer-term plan but not happening imminently.
