### ISSUE TITLE
`brew which-formula lldb` empty for formulas requiring options (eg lldb)

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-command-not-found#38]
brew install llvm --with-lldb => installs lldb
```
brew which-formula lldb
# empty
``` 
would be nice to have:

```
brew which-formula --search_with_options lldb
llvm --with-lldb
```

**Comment by bfontaine** [comment]
It would take a considerably large time to install all formulae with each one of their options in order to discover which option installs which binary.

**Comment by bfontaine** [comment]
I’m closing the issue since nobody is working on it for now.
