### ISSUE TITLE
duplicate 'zsh: command not found: '

### ISSUE THREAD

**Issue by GuanAllen** [Homebrew/homebrew-command-not-found#41]
<img width="537" alt="screen shot 2017-06-03 at 02 24 21 am" src="https://cloud.githubusercontent.com/assets/14134195/26739275/c895c908-4803-11e7-9c8d-26ea9add9247.png">

**Comment by bfontaine** [comment]
This is due to #40. I can reproduce the issue with Zsh 5.2 but not with 5.3.1.

In the meantime you can fix that by installing the latest Zsh: `brew install zsh`.
