### ISSUE TITLE
prompt if not in PATH?

### ISSUE THREAD

**Issue by rdp** [Homebrew/homebrew-command-not-found#71]
```
$ brew install binutils
$ gaddr2line 
zsh: command not found: gaddr2line
```

Would be nice if it said "this should already be installed by package X, perhaps it's not in your PATH"?  Just to avoid confusion for those of us using it :)

**Comment by bfontaine** [comment]
@rdp that’s a good idea; would you want to try to make a pull-request for this feature?

**Comment by rdp** [comment]
Way over my head unfortunately.  Something to consider for the future I suppose
