### ISSUE TITLE
`brew tap` is unnecessary 

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-command-not-found#8]
`brew install` will automatically tap the tap when necessary. Also to be neater , `brew install homebrew/tap/formula` is preferred over `brew install homebrew/homebrew-tap/formula`.

**Comment by xu-cheng** [comment]
I think [these lines](https://github.com/Homebrew/homebrew-command-not-found/blob/bdbb58b9c080e64e2e16f0d76473a15f42da64d4/cmd/brew-which-formula.rb#L53-L55) can be removed. Also, it seems that some methods(`tapped`, `get_tap`, `remove_not_tapped`) would be unnecessary.

**Comment by xu-cheng** [comment]
Nevermind, I can't read the commits log. 

Thanks @bfontaine.

**Comment by bfontaine** [comment]
Yes I removed them in the commit *after* closing the one which closed this issue.
